apiVersion: apps/v1
kind: Deployment
metadata:
  name: quelpoke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quelpoke
  template:
    metadata:
      labels:
        app: quelpoke
    spec:
      containers:
      - name: quelpoke
        image: europe-west9-docker.pkg.dev/$PROJECT_ID/quelpoke-repo/quelpoke:$SHORT_SHA
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: quelpoke-service
spec:
  type: LoadBalancer
  selector:
    app: quelpoke
  ports:
    - port: 80
      targetPort: 8080
